# Pre-commit hooks configuration for code quality and validation
repos:
  # Ruff linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        name: ruff-linting
        args: [--fix, --ignore=F401]  # Auto-fix issues and ignore unused imports
      - id: ruff-format
        name: ruff-formatting

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        name: mypy-type-checking
        args: [--ignore-missing-imports, --disable-error-code=import-untyped, --disable-error-code=attr-defined]  # Ignore missing import types, untyped imports, and attr-defined errors
        additional_dependencies: [types-requests, types-tqdm]

  # File validation hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: trim-trailing-whitespace
      - id: end-of-file-fixer
        name: fix-end-of-files
      - id: check-yaml
        name: validate-yaml-files
        exclude: ^mkdocs\.yml$  # Skip mkdocs.yml
      - id: check-json
        name: validate-json-files
      - id: mixed-line-ending
        name: fix-mixed-line-endings
        args: [--fix=lf]
      - id: check-added-large-files
        name: check-large-files
        args: [--maxkb=1000]
