[project]
name = "web-scraping-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "scrapling>=0.2.99",
    "tqdm>=4.67.1",
]
