name: Core CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  PYTHON_VERSION_DEFAULT: "3.10"
  UV_CACHE_DIR: ~/.cache/uv
  RUFF_IGNORE_RULES: "F401"

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}

      - name: Cache UV dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run ruff linting
        run: uv run ruff check . --fix --ignore=${{ env.RUFF_IGNORE_RULES }}

      - name: Run ruff formatting check
        run: uv run ruff format --check .

      - name: Run mypy type checking
        run: uv run mypy . --ignore-missing-imports --disable-error-code=import-untyped --disable-error-code=attr-defined

      - name: Run core functionality tests
        run: uv run pytest tests/test_main/test_get_page_url.py tests/test_main/test_get_total_pages.py tests/test_main/test_process_book_details.py -v

      - name: Test basic import and syntax
        run: |
          uv run python -c "import main; print('Main module imports successfully')"
          uv run python -c "from utils.logger import logger; print('Logger imports successfully')"
          uv run python -c "from utils.signal_handler import setup_graceful_shutdown; print('Signal handler imports successfully')"

  build-check:
    runs-on: ubuntu-latest
    needs: [code-quality]
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION_DEFAULT }}

      - name: Install UV
        run: pip install uv

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Verify application can start
        run: |
          timeout 10s uv run python main.py --help || true
          echo "Application help command completed"

      - name: Create deployment summary
        run: |
          echo "## Core CI Checks Passed ✅" >> $GITHUB_STEP_SUMMARY
          echo "Essential functionality verified:" >> $GITHUB_STEP_SUMMARY
          echo "- Code quality: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Type checking: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Core tests: ✅" >> $GITHUB_STEP_SUMMARY
          echo "- Import validation: ✅" >> $GITHUB_STEP_SUMMARY
